ai_endpoint: "http://localhost:11434/v1/"
port: 8888
model: "deepseek-r1:14b"
upload_dir: "upload"
weaviate_store_config:
  host: "http://localhost:8080"
  text2vec: "text2vec-transformers"
  module_config:
    text2vec-ollama:
      apiEndpoint: "http://host.docker.internal:11434"
      model: "mxbai-embed-large"
    generative-ollama:
      apiEndpoint: "http://host.docker.internal:11434"
      model: "llama8b"