services:
  mongodb:
    image: mongo:latest
    container_name: chatbot-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    restart: unless-stopped
    command: mongod --auth